"use client";

import { useMemo, useState } from "react";

type Guide = {
  id: string; title: string; section: string; summary: string; time: string; updated: string;
  status: "source-verified" | "draft" | "unit-reviewed"; sourceNote?: string;
  before: string[]; steps: { title: string; text: string; expect?: string; link?: { label: string; href: string }; links?: { label: string; href: string }[] }[];
  problems: string[]; official: { label: string; href: string }[];
  helpful?: { label: string; href: string }[];
};

const statusDetails = {
  "source-verified": { label: "Source-verified", short: "Source-verified" },
  draft: { label: "Draft — pending verification", short: "Draft" },
  "unit-reviewed": { label: "Unit-reviewed", short: "Unit-reviewed" },
};

const sections = [
  { id: "access", title: "Access & Setup", icon: "⌘" },
  { id: "personnel", title: "IPPS-A & Personnel", icon: "◎" },
  { id: "evaluations", title: "Evaluations & NCOERs", icon: "✓" },
  { id: "travel", title: "DTS & Travel", icon: "↗" },
  { id: "forms", title: "Forms & Publications", icon: "▤" },
  { id: "leader", title: "Leader Tools", icon: "◇" },
];

const guides: Guide[] = [
  {
    id: "avd", title: "Set up and access Army AVD", section: "access", time: "15–25 min + training", updated: "23 Aug 2026", status: "source-verified",
    summary: "Request access, connect with Windows App, and use the Army virtual desktop from a Windows or macOS computer.",
    sourceNote: "Compared against the Army IPPS-A AVD instructions dated 23 July 2026, Army AVS baseline-access guidance, Army NETCOM guidance, and current Microsoft Azure Government client guidance.",
    before: ["Active Army 365 @army.mil account", "CAC, PIN, and working CAC reader", "Access to JKO and Army AVS/ICAM"],
    steps: [
      { title: "Complete Cyber Awareness and the Army IT agreement", text: "Before requesting AVD access, make sure your Cyber Awareness Challenge training is current. Open JKO, sign in, and search for the current Cyber Awareness Challenge course; save the completion certificate. Then open Army AVS/ICAM, review and sign the Army IT User Agreement or Authorized Use Policy, submit it through the required approval chain, and confirm that it shows as current. Follow your unit's instructions if it assigns the training through Army ATIS instead of JKO.", expect: "A current Cyber Awareness completion certificate and a completed Army IT agreement/AUP in AVS/ICAM.", links: [{ label: "Open JKO training portal", href: "https://jko.jten.mil/" }, { label: "Open Army AVS/ICAM", href: "https://iga.army.mil/" }] },
      { title: "Choose the right access method", text: "Use Windows App when you need the full experience, including CAC redirection to sites inside AVD or S/MIME email. The government web client is a fallback for basic access, but it does not pass your local smart card into the virtual session.", expect: "Recommended: Windows App on Windows or macOS." },
      { title: "Request Army AVD access", text: "On a CAC-capable computer, open the Army Microsoft MyAccess package. Select Continue, acknowledge the terms, and submit the request. Dual-persona users must complete enrollment separately for each persona they intend to use.", expect: "MyAccess shows that the request was submitted or that access is already assigned.", link: { label: "Open official AVD enrollment", href: "https://myaccess.microsoft.us/@armyeitaas.onmicrosoft.us#/access-packages/b0a616f3-d77c-4f2d-bbb1-5d1bb9c5d709" } },
      { title: "Allow time for provisioning", text: "Army guidance says access is normally created in about 15 minutes and a confirmation is sent to your Army email. No action is required in that email. If the desktop does not appear after about 30 minutes, refresh the client before contacting support.", expect: "Your Army365 AVD resources become available after provisioning." },
      { title: "Install Windows App", text: "Install Microsoft Windows App on your personal Windows or macOS computer. Some Army instructions still call the client Microsoft Remote Desktop; Microsoft has replaced that older client with Windows App for new use.", expect: "The installed application is named Windows App.", link: { label: "Get Windows App for Windows", href: "https://apps.microsoft.com/detail/9N1F85V9T8BN" } },
      { title: "Sign in or add the Army workspace", text: "Open Windows App and sign in with your full @army.mil address. If your Army desktops do not populate automatically, select Add Workspace and enter rdweb.wvd.azure.us. If the client requires the full feed URL, use https://rdweb.wvd.azure.us/api/arm/feeddiscovery.", expect: "An Army365 AVD desktop card appears in Windows App." },
      { title: "Authenticate with your CAC", text: "Insert your CAC, select the Certificate for PIV Authentication, and enter your PIN. Do not choose the email-signing certificate. On macOS, smart-card redirection must be enabled for CAC use inside the virtual desktop.", expect: "CAC authentication completes without a certificate or PIN error." },
      { title: "Connect to the closest desktop", text: "Open the Army365 AVD desktop closest to your location. Depending on the current client, the choices may appear as East/West or Virginia/Arizona. Read and accept the Department of Defense warning banner.", expect: "A Windows 11 Army virtual desktop opens." },
      { title: "Verify the session", text: "Confirm that Army 365 services open. If you used Windows App, test one CAC-enabled site you need inside AVD. Sign out of the virtual desktop when finished; closing only the app window can leave the session running.", expect: "Army 365 works and, when required, the CAC is visible inside the session." },
      { title: "Use the browser only as a fallback", text: "If you cannot install Windows App and only need basic access, open the Army Azure Government web client in Microsoft Edge. Sign in with your full @army.mil address and CAC, then select the closest desktop. Use Windows App instead for downstream CAC-enabled sites or encrypted email.", expect: "The virtual desktop opens in a browser tab with limited device redirection.", link: { label: "Open Army AVD web client", href: "https://client.wvd.azure.us/arm/webclient/index.html" } },
    ],
    problems: ["No desktop appears: confirm the MyAccess entitlement, wait at least 15 minutes, then sign out of Windows App and reopen it.", "CAC certificate is missing or rejected: reconnect the reader, reinsert the CAC, and select Certificate for PIV Authentication—not the email-signing certificate.", "CAC works at sign-in but not inside AVD on a Mac: open the desktop resource settings and confirm Smart cards is enabled under Devices & Audio redirection.", "Two Army personas: each persona needs its own enrollment and workspace. Unsubscribe from the current workspace before switching personas on a shared client.", "Still blocked: contact the Army Enterprise Service Desk at 1-866-335-2769 or use your unit S6 support process."],
    official: [
      { label: "Army IPPS-A AVD instructions — July 2026", href: "https://ipps-a.army.mil/Portals/129/Documents/IPPSA_Hypori_AVD%20Instructions_20260723.pdf" },
      { label: "Army AVS baseline-access guidance", href: "https://www.army.mil/article/284831/army_training_and_certification_tracking_system_sunsetting_may_1_replaced_by_streamlined_account_validation_system" },
      { label: "JKO training portal", href: "https://jko.jten.mil/" },
      { label: "Army AVS/ICAM", href: "https://iga.army.mil/" },
      { label: "Army NETCOM AVD information", href: "https://www.netcom.army.mil/Public/Resource-Types/Information/TechNet25/" },
      { label: "Microsoft: connect with Windows App", href: "https://learn.microsoft.com/en-us/windows-app/get-started-connect-devices-desktops-apps" },
      { label: "Microsoft: Azure Government client transition", href: "https://learn.microsoft.com/en-us/previous-versions/remote-desktop-client/connect-windows-cloud-services" },
      { label: "Army Enterprise Service Desk", href: "https://www.aesmp.army.mil" },
    ],
    helpful: [
      { label: "MilitaryCAC AVD troubleshooting", href: "https://www.militarycac.com/avd.htm" },
      { label: "ArmyLinks AVD registration overview", href: "https://armylinks.com/posts/army-enterprise-azure-virtual-desktop-registration/" },
    ],
  },
  {
    id: "adobe", title: "Make Adobe the default PDF app", section: "access", time: "4–6 min", updated: "23 Aug 2026", status: "source-verified",
    summary: "Make downloaded Army PDF forms open in desktop Acrobat or Acrobat Reader instead of a browser.",
    sourceNote: "Compared against current Adobe Acrobat and Microsoft Windows default-app guidance. Army sources also identify Acrobat Reader as required for some fillable Army forms.",
    before: ["Windows 10 or 11 computer", "Permission to install or use Acrobat", "A downloaded sample PDF"],
    steps: [
      { title: "Install or confirm Adobe Acrobat Reader", text: "Search the Start menu for Adobe Acrobat or Acrobat Reader. If neither is installed on a personal computer, download Acrobat Reader from Adobe. On government equipment, use the approved Software Center or contact your support office instead of installing unapproved software.", expect: "Adobe Acrobat or Acrobat Reader appears in the Start menu.", link: { label: "Get Adobe Acrobat Reader", href: "https://get.adobe.com/reader/" } },
      { title: "Download the PDF first", text: "When an Army form opens in a browser tab, select Download or Save a copy and save it to your computer. Browser PDF viewers can display a form while hiding or limiting fillable fields and certificate-signing features.", expect: "A .pdf file is saved in Downloads or another known folder." },
      { title: "Open the PDF properties", text: "In File Explorer, right-click the downloaded PDF and select Properties. On the General tab, locate Opens with and select Change.", expect: "The file Properties window shows a Change button beside Opens with." },
      { title: "Choose Adobe as the default", text: "Select Adobe Acrobat or Adobe Acrobat Reader, then select Set default. Return to the Properties window and select OK. If both applications are installed, Adobe recommends setting Acrobat as the default.", expect: "The PDF file icon changes to Adobe and Properties lists Adobe beside Opens with.", link: { label: "Adobe default-app instructions", href: "https://helpx.adobe.com/acrobat/desktop/get-started/preferences-and-settings/set-default-acrobat.html" } },
      { title: "Use Windows Settings if needed", text: "If the Properties method is unavailable, open Settings > Apps > Default apps. Search for .pdf, select the current application, and choose Adobe Acrobat or Acrobat Reader. Organization-managed computers may prevent this change.", expect: ".pdf is associated with Adobe in Windows Default apps.", link: { label: "Microsoft default-app instructions", href: "https://support.microsoft.com/en-us/windows/apps/change-default-apps-in-windows" } },
      { title: "Verify with a downloaded form", text: "Close the browser and double-click the saved PDF. Confirm it opens in the desktop Adobe application. A PDF link may still preview inside a browser; download it or choose Open in desktop app when you need fillable fields or a CAC signature.", expect: "The file opens in desktop Acrobat or Acrobat Reader—not in an Edge or Chrome tab." },
    ],
    problems: ["Adobe is not listed: install Acrobat Reader on a personal device or request the approved application on government equipment.", "The Change button is disabled: the device may be organization-managed; contact your local help desk or S6.", "The browser still opens PDF links: the Windows default controls downloaded files, not every browser preview. Download the PDF, then open the saved file.", "The form displays a Please wait message or missing fields: save the PDF locally and open it directly in desktop Acrobat Reader.", "The form opens in Adobe but cannot be edited: it may be protected, already signed, or require a different version. Obtain a fresh official copy before altering it."],
    official: [
      { label: "Adobe: set Acrobat as the default PDF program", href: "https://helpx.adobe.com/acrobat/desktop/get-started/preferences-and-settings/set-default-acrobat.html" },
      { label: "Microsoft: change default apps in Windows", href: "https://support.microsoft.com/en-us/windows/apps/change-default-apps-in-windows" },
      { label: "Adobe Acrobat Reader download", href: "https://get.adobe.com/reader/" },
      { label: "Army MEDCoE example: forms requiring Acrobat Reader", href: "https://medcoe.army.mil/efmb/" },
    ],
  },
  {
    id: "sign-pdf", title: "Digitally sign a PDF with your CAC", section: "access", time: "6–10 min", updated: "23 Aug 2026", status: "source-verified",
    summary: "Apply a certificate-based CAC signature in desktop Acrobat and verify the signed file before sending it.",
    sourceNote: "Compared against current Adobe certificate-signing and validation guidance plus Army examples requiring CAC-signed PDF documents.",
    before: ["Downloaded PDF open in desktop Acrobat", "CAC inserted and PIN available", "All required fields completed and reviewed"],
    steps: [
      { title: "Save an unsigned working copy", text: "Download the PDF and open it in desktop Acrobat or Acrobat Reader—not inside the browser. Complete the required fields, review the document, and save an unsigned working copy before signing. A digital signature can restrict later changes.", expect: "The completed, unsigned PDF is saved locally with a clear file name." },
      { title: "Use a certificate—not Fill & Sign", text: "If the form has a designated digital-signature field, select it. Otherwise, select All tools > Use a certificate > Digitally sign, acknowledge the prompt, and draw a rectangle where the signature belongs. A typed or drawn Fill & Sign mark is not a CAC certificate signature.", expect: "The Sign with a Digital ID window opens.", link: { label: "Adobe digital-signature instructions", href: "https://helpx.adobe.com/acrobat/desktop/e-sign-documents/fill-sign-documents/add-digital-sign.html" } },
      { title: "Select the CAC digital ID", text: "Choose the certificate from your CAC that Acrobat shows as valid for digital signing, then select Continue. Do not create or use a self-signed Digital ID for an official Army form. If your unit or the form specifies a particular CAC certificate, follow that instruction.", expect: "Acrobat displays your name and CAC-issued signing identity." },
      { title: "Review the signature settings", text: "Confirm your name and signature appearance. Leave Lock document after signing unchecked when another person must sign or edit the form. Select it only when the form instructions require locking or you are the final signer.", expect: "The signature preview is correct and the locking choice matches the form workflow." },
      { title: "Enter your CAC PIN and save", text: "Select Sign, enter your CAC PIN only in the certificate prompt, and save the signed document with a new file name. Do not overwrite the unsigned working copy until you confirm the signature worked.", expect: "The signature appears and Acrobat reports that the document was signed." },
      { title: "Validate the saved signature", text: "Close and reopen the signed file. Open the Signatures panel and review the status. If needed, select Options > Validate Signatures and open Signature Properties to review the certificate details.", expect: "The signature panel identifies the signer and reports a valid signature or explains the trust issue.", link: { label: "Adobe signature-validation instructions", href: "https://helpx.adobe.com/acrobat/desktop/e-sign-documents/manage-digital-signatures/validate-digital-sign.html" } },
      { title: "Send through an approved method", text: "Use the file-naming convention and submission method required by the form, system, or unit. Handle documents containing personal or controlled information only through approved Army channels.", expect: "The correct signed version is ready for the required Army workflow." },
    ],
    problems: ["No CAC identity appears: close Acrobat, insert the CAC, reopen Acrobat, and try again. Confirm the reader and CAC work in another approved application.", "Only Configure New Digital ID appears: do not create a self-signed identity for an official Army form. Reconnect the CAC and contact local support if Acrobat still cannot see it.", "The signature field is locked or unavailable: the form may already be signed, certified, protected, or awaiting a different signer. Start from the official unsigned copy or contact the form owner.", "The next signer cannot edit the form: the document may have been locked during signing. Return to the unsigned working copy and repeat the signing process without locking it, if permitted.", "The signature becomes invalid after editing: certificate signatures protect document integrity. Obtain the unsigned source, make authorized corrections, and sign again.", "Acrobat reports an unknown or untrusted signer: open Signature Properties to inspect the certificate and use your organization's approved trust configuration; do not mark an unfamiliar certificate as trusted without authorization."],
    official: [
      { label: "Adobe: add digital signatures", href: "https://helpx.adobe.com/acrobat/desktop/e-sign-documents/fill-sign-documents/add-digital-sign.html" },
      { label: "Adobe: validate digital signatures", href: "https://helpx.adobe.com/acrobat/desktop/e-sign-documents/manage-digital-signatures/validate-digital-sign.html" },
      { label: "Adobe: digital ID overview", href: "https://helpx.adobe.com/acrobat/desktop/protect-documents/manage-digital-ids/digital-ids.html" },
      { label: "Army example: CAC-sign and save a PDF", href: "https://g6msd.redstone.army.mil/usingEDIS.html" },
    ],
  },
  {
    id: "ippsa", title: "Access and navigate IPPS-A Self-Service", section: "personnel", time: "8–12 min", updated: "23 Aug 2026", status: "source-verified",
    summary: "Use the current myAuth login, identify the correct IPPS-A portal, and locate your profile, requests, forms, and official help.",
    sourceNote: "Compared against IPPS-A's 29 July 2026 myAuth transition notice, the August 2026 Mobile page, the February and April 2026 customer-support products, and current Self-Service navigation guidance.",
    before: ["A myAuth account or an existing DS Logon for first-time setup", "CAC and reader available as a backup sign-in method", "Okta Verify or another myAuth security method"],
    steps: [
      { title: "Choose Self-Service—not the elevated portal", text: "Most Soldiers completing their own actions use my.ippsa.army.mil. The hr.ippsa.army.mil address is for elevated HR Professional, Commander, and other authorized roles. Using the wrong portal can create a misleading access or permission error.", expect: "You are opening the Self-Service portal for your own records and requests.", links: [{ label: "Open IPPS-A Self-Service", href: "https://my.ippsa.army.mil" }, { label: "Review official login transition", href: "https://ipps-a.army.mil/Resources/News/Article/4558971/ipps-a-login-is-transitioning-to-myauth/" }] },
      { title: "Sign in with myAuth", text: "Since 17 August 2026, IPPS-A Self-Service requires myAuth on any device and any network. If you still have DS Logon but have not created myAuth, start the login and follow the prompt to create the new account. Once myAuth is configured, sign in with the security method you established; CAC remains an optional login method.", expect: "myAuth completes authentication and opens the IPPS-A Self-Service homepage." },
      { title: "Set up Okta Verify if required", text: "If myAuth directs you to configure Okta Verify, install the official Okta Verify app, open myAuth Account Settings on a CAC-capable computer, select Manage Security Methods, and follow the Okta Verify setup. Scan the displayed QR code only inside the official myAuth setup flow.", expect: "Okta Verify is registered to your myAuth account and can approve sign-in.", link: { label: "Open official myAuth portal", href: "https://myauth.dmdc.mil" } },
      { title: "Understand when AVD is required", text: "Self-Service no longer requires AVD merely because you are on a personal device. Elevated users opening hr.ippsa.army.mil from a personal computer must use Army AVD. Other official elevated-access paths are Army BYOD/Hypori on a personal phone, NIPR or VPN on government equipment, and Hypori on supported GFE phones.", expect: "Your access method matches the portal and role you are trying to use.", link: { label: "Review IPPS-A mobile and access guidance", href: "https://ipps-a.army.mil/Drive-the-Change/Mobile/" } },
      { title: "Locate the main Soldier functions", text: "On the Self-Service homepage, use the tiles or Search in Menu. Common functions include My Personnel Action Requests, My Soldier Talent Profile, Personal Details, My Orders, DD Form 93, retirement points, assignment elections, and the Pay-Absence-Incent-Deduction (PAID) tile. Tile placement can change during releases, so search by function name when it is not visible.", expect: "You can locate the function by tile or menu search without relying on an old screenshot." },
      { title: "Review your Personal Details", text: "Open Personal Details and verify your home address, preferred email address, and phone number. Correct information here can affect downstream workflows and leader contact information. Do not change official data merely to make another transaction pass; resolve the underlying discrepancy with S-1.", expect: "Your contact and address information is accurate or the discrepancy is documented for correction." },
      { title: "Review your Soldier Talent Profile", text: "Open Talent Management Soldier Workcenter > My Soldier Talent Profile, or search for My Soldier Talent Profile. Review the information that matters to your current action, including assignment, service, qualifications, education, and readiness data. Some values come from other source systems and cannot be edited directly in the STP.", expect: "You know which data is correct and which items need a source-system update or personnel action." },
      { title: "Use the current help inside IPPS-A", text: "Open the Actions menu in the upper-right corner and select Help. If the resource you need is hidden, uncheck Applicable. For a system problem, open Help & Training > IPPS-A Help Center, search the FAQs, or select Create a Case. Use My Cases to track that help request.", expect: "You are using the current Self-Service Guide, User Manual, job aid, or a trackable CRM support case.", links: [{ label: "IPPS-A Training Aids", href: "https://ipps-a.army.mil/Training/Training-Aids/" }, { label: "IPPS-A Customer Support", href: "https://ipps-a.army.mil/Contact/Customer-Support/" }] },
      { title: "Sign out when finished", text: "Save only the records you are authorized to retain, close open personnel documents, and sign out of IPPS-A and myAuth. On a shared or public computer, close the browser and remove downloaded files containing personal information.", expect: "The session is closed and no personal documents remain exposed on a shared device." },
    ],
    problems: ["Self-Service login asks for DS Logon: follow the transition prompt to create myAuth; DS Logon is being replaced, not retained as the long-term login.", "The portal says you lack permission: confirm you used my.ippsa.army.mil for your own actions. Elevated roles require authorization and a separate approved access path.", "A tile is missing: use Search in Menu because IPPS-A reorganizes homepage tiles during releases.", "CAC authentication fails: use the configured myAuth method for Self-Service, or reconnect the CAC and select the PIV Authentication certificate when using optional CAC login.", "A profile value is wrong but cannot be edited: identify the source document and contact S-1; many STP fields are fed by another system or require a PAR.", "You cannot access elevated functions from a personal computer: open Army AVD and use hr.ippsa.army.mil inside the virtual desktop.", "Still locked out: use IPPS-A Customer Support or call 1-844-474-7772. Technical access problems belong in a CRM case, not a personnel-action PAR."],
    official: [
      { label: "IPPS-A Self-Service login", href: "https://my.ippsa.army.mil" },
      { label: "IPPS-A myAuth transition — July 2026", href: "https://ipps-a.army.mil/Resources/News/Article/4558971/ipps-a-login-is-transitioning-to-myauth/" },
      { label: "IPPS-A mobile and access guidance — Aug 2026", href: "https://ipps-a.army.mil/Drive-the-Change/Mobile/" },
      { label: "IPPS-A Customer Support", href: "https://ipps-a.army.mil/Contact/Customer-Support/" },
      { label: "IPPS-A Training Aids", href: "https://ipps-a.army.mil/Training/Training-Aids/" },
      { label: "IPPS-A Self-Service update — Sept 2025", href: "https://ipps-a.army.mil/Resources/News/Article/4294547/ipps-a-update-self-service-homepage-contact-info-absence-reasons-leaders-report/" },
    ],
  },
  {
    id: "ippsa-par", title: "Submit and track an IPPS-A personnel action", section: "personnel", time: "10–20 min", updated: "23 Aug 2026", status: "source-verified",
    summary: "Create a Personnel Action Request (PAR), attach the correct evidence, validate it, submit it, and monitor the action without creating duplicates.",
    sourceNote: "Compared against current IPPS-A Training Aids, the 2026 Self-Service PAR workflow shown in the official Continuation Pay job aid, AR 600-8 implementation guidance, and current IPPS-A help and routing guidance. Exact action categories and attachments remain request-specific.",
    before: ["The exact personnel action and effective date", "Current official source documents saved as readable files", "Your unit's PAR category, attachment, and routing instructions"],
    steps: [
      { title: "Confirm that a PAR is the correct workflow", text: "Use a Personnel Action Request for a personnel or record action available in IPPS-A. A PAR is not a general help ticket. Technical access problems, system errors, and how-to support belong in a CRM case through the IPPS-A Help Center. Ask S-1 before submitting when you do not know the correct Action and Reason.", expect: "You know whether to submit a personnel-action PAR or a technical-support CRM case." },
      { title: "Identify the exact Action and Reason", text: "Use the current official job aid, regulation, MILPER message, or unit SOP for the action. Do not automatically select Admin Records Corrections > Other because it seems flexible; some actions have dedicated categories and routing. Confirm the effective date and approval authority before beginning.", expect: "You have the correct Action, Reason, effective date, and required evidence." },
      { title: "Prepare the supporting documents", text: "Download current official forms when required, complete every applicable field, obtain required signatures, and save readable PDFs with clear file names. Attach only required documents. Verify that dates, names, and identifiers agree across the request and attachments, and protect all PII through approved systems.", expect: "Each required document is current, readable, signed when required, and consistent with the request." },
      { title: "Open My Personnel Action Requests", text: "Sign in to IPPS-A Self-Service and open My Personnel Action Requests. If the tile is not visible, look under My Soldier Data or use Search in Menu. Select Create Personnel Action.", expect: "The Create Personnel Action page opens for your record.", link: { label: "Open IPPS-A Self-Service", href: "https://my.ippsa.army.mil" } },
      { title: "Enter the request information", text: "Enter the effective date, select the correct Action, select the matching Reason, and continue. Complete every action-specific field. In More Information, state what you are requesting, the relevant date or period, and what the attached evidence supports. Keep the explanation factual and concise.", expect: "The request category and narrative describe the same action supported by the documents." },
      { title: "Attach the evidence", text: "Select Add Attachment and upload the required supporting files. Open or preview each attachment when possible to confirm it is the intended document, upright, legible, and complete. Do not upload unrelated records or more PII than the action requires.", expect: "Every required attachment appears once and can be read by the reviewer." },
      { title: "Validate and review", text: "Select Validate and resolve every error. When validation passes, select Next and review the Transaction Summary. Recheck the Soldier, effective date, Action, Reason, narrative, and attachment list before submitting.", expect: "Validation passes and the Transaction Summary matches the intended request." },
      { title: "Submit and record the transaction", text: "Select Submit, confirm submission, and acknowledge the final notification. Record the transaction or request number when displayed. A submitted PAR has entered the workflow; it is not the same as final approval or a completed record change.", expect: "The PAR appears in My Personnel Action Requests with a submitted status and identifying number." },
      { title: "Track the same PAR", text: "Return to My Personnel Action Requests to monitor status and review comments. If the request is returned or pushed back, open the existing transaction, read the reviewer comment, correct the identified issue, and resubmit through the available workflow. Do not create a second PAR for the same action unless S-1 directs you to do so.", expect: "There is one active request for the action, and any correction stays connected to its history." },
      { title: "Verify the final result", text: "After approval, verify the intended change in the correct record, order, STP field, iPERMS document, or later LES as applicable. Some approved actions still require downstream HR or finance processing. If the result is missing, provide S-1 the approved PAR number and supporting evidence instead of starting over.", expect: "The underlying record or pay result—not only the PAR status—shows the completed action." },
    ],
    problems: ["You cannot find the right Action or Reason: stop and ask S-1; choosing Other can send the request into the wrong workflow.", "Validate produces an error: correct the highlighted field or required attachment before proceeding; do not bypass validation with a different category.", "The attachment will not open: replace it with a readable PDF and confirm the complete document uploaded.", "The request was returned without an obvious reason: open its comments and history, then contact the listed reviewer or S-1 pool with the PAR number.", "The PAR remains pending: use its number and current routing status when following up; repeated duplicate submissions make resolution harder.", "The PAR shows approved but the record is unchanged: allow the applicable processing time, then ask S-1 to verify downstream completion or finance transmission.", "You have a login or system error rather than a personnel action: create a CRM case through Help & Training > IPPS-A Help Center."],
    official: [
      { label: "IPPS-A Self-Service login", href: "https://my.ippsa.army.mil" },
      { label: "IPPS-A Training Aids", href: "https://ipps-a.army.mil/Training/Training-Aids/" },
      { label: "Official 2026 PAR workflow example", href: "https://ipps-a.army.mil/Portals/129/Documents/Job%20Aid_Continuation%20Pay_20260401.pdf" },
      { label: "IPPS-A Customer Support", href: "https://ipps-a.army.mil/Contact/Customer-Support/" },
      { label: "AR 600-8 — Military Human Resources Management", href: "https://armypubs.army.mil/epubs/DR_pubs/DR_a/ARN43237-AR_600-8-000-WEB-1.pdf" },
      { label: "IPPS-A implementation guidance — June 2026", href: "https://ipps-a.army.mil/Portals/129/Documents/IPPS-A%20Implementation%20Guidance_ARN46677-ALARACT_20260602.pdf" },
    ],
  },
  {
    id: "ncoer", title: "Access EES and sign an NCOER", section: "evaluations", time: "6 min", updated: "Pending", status: "draft", summary: "Review the evaluation carefully, sign with CAC, and verify completion.", before: ["CAC access", "Evaluation assigned and ready for your signature", "Time to review every entry"],
    steps: [{ title: "Open EES", text: "Use the Evaluation Entry System from an approved Army access path." }, { title: "Review the evaluation", text: "Confirm administrative information, rating period, duty description, and narrative comments before signing." }, { title: "Select the proper certificate", text: "Use the PIV Authentication certificate when prompted by the system." }, { title: "Sign and verify", text: "Complete the signature action and verify the evaluation status changed as expected." }],
    problems: ["Do not sign an evaluation you have not reviewed.", "If the evaluation is unavailable or incorrect, contact the rater, senior rater, or unit S1."], official: [],
  },
  {
    id: "dts", title: "Create a DTS authorization", section: "travel", time: "10 min", updated: "Pending", status: "draft", summary: "Start travel correctly and send the authorization through your unit’s routing process.", before: ["Unit travel instructions", "Approved travel dates and location", "Correct line of accounting and routing guidance"],
    steps: [{ title: "Create an authorization", text: "Open DTS, choose Create New Document, and select Authorization." }, { title: "Enter itinerary and reservations", text: "Enter only the travel that your unit has authorized. Keep receipts and supporting documents." }, { title: "Review expenses", text: "Check transportation, lodging, rental car, and per diem against unit instructions." }, { title: "Sign and submit", text: "Digitally sign the authorization and send it through the assigned routing list." }],
    problems: ["Do not guess a line of accounting or routing official—ask the ODTA or unit travel point of contact.", "A returned document normally includes reviewer comments; correct the listed issue before resubmitting."], official: [{ label: "Open DTS", href: "https://dtsproweb.defensetravel.osd.mil" }],
  },
  {
    id: "armypubs", title: "Find current Army regulations and forms", section: "forms", time: "5–8 min", updated: "23 Aug 2026", status: "source-verified",
    summary: "Use the Army Publishing Index to find an active publication or form, verify its edition, and download the official file.",
    sourceNote: "Compared against the current Army Publishing Directorate index, search instructions, and APD warnings about unofficial forms and dynamic PDFs.",
    before: ["Publication or form number when available", "A few words from the official title if the number is unknown", "Desktop Adobe Acrobat or Reader for fillable forms"],
    steps: [
      { title: "Open the Army Publishing Index", text: "Use the official Army Publishing Directorate index instead of starting with a general search engine. The index can search publications and forms by number, title, proponent, date, and status.", expect: "The page heading says Army Publishing Index and the address ends in armypubs.army.mil.", link: { label: "Open Army Publishing Index", href: "https://armypubs.army.mil/ProductMaps/PubForm/ActiveInactiveRescSearch.aspx" } },
      { title: "Search by the exact number", text: "Enter the publication or form designator in the Pub/Form Number field. Use the full type and number—for example, AR 600-9, ATP 6-22.1, or DA Form 4856. APD warns that typing DA 4856 instead of DA Form 4856 may return no records.", expect: "The result matches the number you intended to find." },
      { title: "Use title or content search when needed", text: "If you do not know the number, enter a few words from the official title. If that does not work, use APD Content Search to look inside hosted publications. Start with one field, then add filters only if there are too many results.", expect: "You have a short result list that can be checked individually.", link: { label: "Open APD Content Search", href: "https://armypubs.army.mil/ProductMaps/PubForm/ContentSearch.aspx" } },
      { title: "Confirm the record before using it", text: "Open the record details and verify the Pub/Form Number, title, publication date, proponent, and prescribing directive when shown. For current work, confirm the status says ACTIVE. Inactive, rescinded, or superseded material may be useful for research but should not be treated as current guidance.", expect: "The record details show the expected document and an ACTIVE status." },
      { title: "Download from the official record", text: "Select the PDF or other unit-of-issue link on the APD record. Dynamic forms may show a Please wait message in the browser; download the file first and open it in desktop Adobe Acrobat or Reader.", expect: "The saved file opens from an official .mil source and displays correctly in Adobe." },
      { title: "Check the identifiers on a form", text: "Before entering personal information, verify the form title, the prescribing-publication or for-use line, and the proponent. APD says the form number and date appear at the lower left and the version appears at the lower right. Do not enter PII into a form copied from an unofficial site.", expect: "The form identifiers agree with the ACTIVE APD record." },
      { title: "Record what you used", text: "For leader products, note the publication or form number and edition date. Recheck APD before reusing an old saved copy because the official file can be revised without your local copy changing.", expect: "Someone reviewing the product can identify the exact source and edition." },
    ],
    problems: ["No records: use the complete designator, such as DA Form 4856—not DA 4856—and remove extra filters.", "Too many records: add the title, proponent, or ACTIVE status filter.", "PDF displays Please wait: download it and open the saved file in desktop Acrobat or Acrobat Reader.", "A search-engine copy looks newer: do not rely on it until the number, date, status, and official APD record agree.", "The document is missing from APD: check the record status and footnotes; some publications are hosted on another officially approved government site."],
    official: [
      { label: "Army Publishing Index", href: "https://armypubs.army.mil/ProductMaps/PubForm/ActiveInactiveRescSearch.aspx" },
      { label: "APD Content Search", href: "https://armypubs.army.mil/ProductMaps/PubForm/ContentSearch.aspx" },
      { label: "APD frequently asked questions", href: "https://armypubs.army.mil/FAQ/FAQ1.aspx" },
      { label: "Active DA Form 4856 record", href: "https://armypubs.army.mil/ProductMaps/PubForm/Details.aspx?PUB_ID=1026753" },
      { label: "Active DA Form 5960 record", href: "https://armypubs.army.mil/ProductMaps/PubForm/Details.aspx?PUB_ID=1024365" },
    ],
  },
  {
    id: "bah-5960", title: "Start or recertify BAH (DA Form 5960)", section: "forms", time: "8–15 min", updated: "23 Aug 2026", status: "source-verified",
    summary: "Use the current IPPS-A housing workflow for CONUS BAH certification or recertification and understand when S-1 or finance must act.",
    sourceNote: "Compared against the December 2025 IPPS-A BAH Initial Certification and BAH Recertification job aids, the current IPPS-A Training Aids page, and the active January 2022 DA Form 5960 record on APD.",
    before: ["CAC access to IPPS-A", "Correct home address and duty assignment in IPPS-A", "Dependency information and any documents required by unit SOP"],
    steps: [
      { title: "Choose the correct action", text: "Use this process only when you need an initial CONUS BAH certification or annual recertification. IPPS-A calls the generated document the BAH Authorization and Dependency Declaration, previously known as DA Form 5960. OCONUS members use the legacy OHA process. If your entitlement, dependency status, or address changed, notify S-1 or finance instead of treating it as a routine recertification.", expect: "You know whether the request is an initial certification, annual recertification, or a change requiring S-1/finance." },
      { title: "Confirm your home address", text: "In IPPS-A, review Self-Service > My Soldier Data > Personal Details > Home Address. Add or correct the address before starting if it is missing. The housing request cannot populate Primary Residence when no home address is available.", expect: "Your correct primary residence is available for selection in the housing request.", link: { label: "Open IPPS-A", href: "https://hr.ippsa.army.mil/" } },
      { title: "Start an initial BAH certification", text: "From the Self-Service homepage, open the Pay-Absence-Incent-Deduction (PAID) tile. Under Selection Criteria, choose Entry Type: Housing, leave Status blank, select Add, and choose Housing Category: BAH.", expect: "A new Housing request opens with BAH selected.", link: { label: "Official initial-certification job aid", href: "https://ipps-a.army.mil/Portals/129/Documents/Job%20Aid_BAH%20Initial%20Certification_20251211.pdf" } },
      { title: "Enter the housing details", text: "Select the begin date and an end date one year later. Complete the quarters type, housing type, primary residence, duty assignment, BAH-based-on postal location, spouse information, and additional dependents as applicable. Do not guess an entitlement category; stop and ask S-1 or finance when the correct selection is unclear.", expect: "The housing dates, address, assignment, and dependency information are complete and accurate." },
      { title: "Follow the unit document requirements", text: "The IPPS-A initial-certification job aid says comments and attachments are not universally required; organizational SOP determines what to include. Use only the supporting documents requested by your S-1 or finance office and send PII through an approved channel.", expect: "The request contains exactly the documents and comments required by the unit—not unnecessary PII." },
      { title: "Submit the initial certification", text: "Review every entry and select Submit. The request routes to the Member's S-1 pool. IPPS-A certification itself does not change pay; S-1 must transmit an initial certification or BAH status change to the Army Military Pay Office for pay action.", expect: "The request is submitted and visible in IPPS-A with a trackable status." },
      { title: "Complete annual recertification", text: "For an approved CONUS BAH entry, open PAID, choose Entry Type: Housing and Status: Approved, select Search, and open the Amend/View icon. Select Update Dates, extend the end date for one year, then submit.", expect: "The updated recertification routes to the S-1 pool.", link: { label: "Official recertification job aid", href: "https://ipps-a.army.mil/Portals/129/Documents/Job%20Aid_BAH%20Recertification_20251211.pdf" } },
      { title: "Verify the result", text: "Monitor the request in IPPS-A and respond to returned comments. For a pay-impacting action, verify the change on a later LES after S-1 and finance complete processing. Confirm the BAH document is filed in iPERMS when applicable; do not assume a submitted request has changed your pay.", expect: "The request is approved, required records are filed, and any expected pay change is confirmed on the LES." },
      { title: "Use the paper form only when directed", text: "If S-1 or finance specifically requires a PDF, download the ACTIVE January 2022 DA Form 5960 from APD, complete the applicable member sections, sign it, and obtain the commander certification through the unit process. Never use an older copy from a general search result.", expect: "Any paper DA Form 5960 matches the active APD record and follows the unit's submission procedure.", links: [{ label: "Open active DA Form 5960 record", href: "https://armypubs.army.mil/ProductMaps/PubForm/Details.aspx?PUB_ID=1024365" }, { label: "Download active DA Form 5960", href: "https://armypubs.army.mil/pub/eforms/DR_a/ARN46930-DA_FORM_5960-101-EFILE-2.pdf" }] },
    ],
    problems: ["Primary Residence is blank: add or correct Home Address under My Soldier Data > Personal Details, save it, then return to the housing request.", "You need to change BAH—not merely recertify it: contact S-1 or finance because certification in IPPS-A is non-pay-impacting by itself.", "You are OCONUS: do not use the CONUS BAH workflow; follow the legacy OHA certification or recertification process.", "The first IPPS-A entry appears as Start: this can occur because older BAH data was not converted into the housing request history; confirm with S-1 before changing it.", "The request was returned: read the approver comments, correct only the identified issue, and resubmit through the same workflow.", "The request is approved but the LES is unchanged: provide the approved transaction information to S-1 so they can verify transmission to the Army Military Pay Office."],
    official: [
      { label: "IPPS-A Training Aids", href: "https://ipps-a.army.mil/Training/Training-Aids/" },
      { label: "BAH Initial Certification job aid — Dec 2025", href: "https://ipps-a.army.mil/Portals/129/Documents/Job%20Aid_BAH%20Initial%20Certification_20251211.pdf" },
      { label: "BAH Recertification job aid — Dec 2025", href: "https://ipps-a.army.mil/Portals/129/Documents/Job%20Aid_BAH%20Recertification_20251211.pdf" },
      { label: "DA Form 5960 APD record — Active, Jan 2022", href: "https://armypubs.army.mil/ProductMaps/PubForm/Details.aspx?PUB_ID=1024365" },
      { label: "IPPS-A BAH workflow update", href: "https://ipps-a.army.mil/Resources/News/Article/4017945/ipps-a-update-2nd-anniversary-submit-pcs-event-bah-recertification-pai-reconcil/" },
    ],
  },
  {
    id: "counseling", title: "Complete a developmental counseling", section: "leader", time: "15–25 min", updated: "23 Aug 2026", status: "source-verified",
    summary: "Plan, conduct, document, and assess a developmental counseling using the active DA Form 4856.",
    sourceNote: "Compared against the active March 2023 DA Form 4856 record, ATP 6-22.1, and the Army's 2023 explanation of the dynamic counseling templates.",
    before: ["A specific counseling purpose and desired outcome", "Relevant facts, standards, and examples", "Private setting with enough time for a two-way discussion"],
    steps: [
      { title: "Download the active DA Form 4856", text: "Use the ACTIVE March 2023 Developmental Counseling Form from Army Publishing Directorate. Download it before opening it because it is a dynamic PDF and may not work in a browser viewer. Open the saved file in desktop Adobe Acrobat or Reader.", expect: "The form shows DA Form 4856, MAR 2023 and offers counseling-template choices.", links: [{ label: "Open active DA Form 4856 record", href: "https://armypubs.army.mil/ProductMaps/PubForm/Details.aspx?PUB_ID=1026753" }, { label: "Download active DA Form 4856", href: "https://armypubs.army.mil/pub/eforms/DR_a/ARN46840-DA_FORM_4856-104-EFILE-4.pdf" }] },
      { title: "Select the counseling type and approach", text: "Choose Performance, Professional Growth, Event-Oriented, or General based on the actual purpose. Then decide whether the approach should be nondirective, directive, or combined. The built-in templates are aids; commanders still own their counseling programs and may set additional requirements.", expect: "The selected template and approach fit the situation—not merely the most familiar option." },
      { title: "Plan the session before writing", text: "Define the desired outcome, identify the standard or behavior involved, gather firsthand facts and specific examples, and choose a suitable location and time. For performance or event counseling, separate observed facts from assumptions and personal opinions.", expect: "You can explain what happened, the applicable standard, and what should happen next using specific facts." },
      { title: "Complete the administrative data and purpose", text: "Enter the Soldier, rank or grade, date, organization, counselor name, and title. Write a concise purpose statement that tells the Soldier why the session is occurring and identifies the relevant event, performance area, or development goal.", expect: "Part I is accurate and the purpose is clear before the discussion begins." },
      { title: "Conduct a two-way discussion", text: "Explain the purpose, review the facts and standards, ask open-ended questions, and listen to the Soldier's perspective. Use the selected approach to guide the conversation. Counseling is the discussion; the form records the important results.", expect: "Both people understand the issue, contributing factors, and desired outcome." },
      { title: "Record the key points", text: "Document the essential discussion in clear, professional language. Use dates, actions, standards, and observable behavior when relevant. Avoid insults, diagnoses, exaggeration, copied boilerplate, or conclusions you cannot support.", expect: "Another authorized leader could understand what was discussed without guessing." },
      { title: "Build a measurable plan of action", text: "List what the Soldier will do, who will assist, the completion dates, and how progress will be measured. Add the leader responsibilities needed to support the plan. Replace vague statements such as improve attitude with observable actions and deadlines.", expect: "The plan identifies specific actions, responsible people, dates, and a measurable result." },
      { title: "Review remarks and signatures", text: "Give the Soldier time to read the completed counseling and enter individual remarks. Correct factual errors before finalizing. Complete the signature process required by the form and unit policy, then provide or retain copies through an approved method.", expect: "The final counseling reflects the discussion and both parties know what happens next." },
      { title: "Assess the plan of action", text: "Set a follow-up date instead of treating the signature as the end of the process. At follow-up, complete Part IV with the Soldier, record whether the plan achieved the intended results, and revise the plan or conduct additional counseling when needed.", expect: "Part IV records the outcome and any required next action." },
    ],
    problems: ["The form shows Please wait: save it locally and open it in desktop Acrobat or Acrobat Reader.", "The wrong template was selected: return to a fresh official copy and choose the type that matches the counseling purpose.", "The counseling contains only conclusions: add dates, observed behavior, the applicable standard, and the impact.", "The plan says improve or do better: replace it with an observable action, responsible person, deadline, and measure of success.", "The Soldier disputes the counseling: document the Soldier's remarks accurately and elevate factual or procedural disputes through the chain of command.", "The matter could support adverse action or separation: coordinate with the commander and servicing legal office; a generic counseling template is not legal review.", "Sensitive information must be transmitted: use an approved Army channel and limit access to people with an official need to know."],
    official: [
      { label: "DA Form 4856 APD record — Active, Mar 2023", href: "https://armypubs.army.mil/ProductMaps/PubForm/Details.aspx?PUB_ID=1026753" },
      { label: "Download active DA Form 4856", href: "https://armypubs.army.mil/pub/eforms/DR_a/ARN46840-DA_FORM_4856-104-EFILE-4.pdf" },
      { label: "ATP 6-22.1 — The Counseling Process", href: "https://armypubs.army.mil/epubs/DR_pubs/DR_a/pdf/web/atp6_22x1.pdf" },
      { label: "Army article: 2023 counseling-form update", href: "https://www.army.mil/article/264745/leaders_take_note_the_armys_counseling_form_gets_a_much_needed_update" },
    ],
  },
];

export default function Home() {
  const [activeId, setActiveId] = useState<string | null>(null);
  const [openSections, setOpenSections] = useState<string[]>(["access"]);
  const [query, setQuery] = useState("");
  const [menuOpen, setMenuOpen] = useState(false);
  const active = activeId ? guides.find((guide) => guide.id === activeId) ?? null : null;
  const filtered = useMemo(() => {
    const search = query.trim().toLowerCase();
    if (!search) return guides;
    return guides.filter((guide) => [
      guide.title,
      guide.section,
      guide.summary,
      ...guide.before,
      ...guide.steps.flatMap((step) => [step.title, step.text]),
      ...guide.official.map((source) => source.label),
    ].join(" ").toLowerCase().includes(search));
  }, [query]);
  const selectGuide = (id: string) => { setActiveId(id); setMenuOpen(false); const section = guides.find((guide) => guide.id === id)?.section; if (section && !openSections.includes(section)) setOpenSections((current) => [...current, section]); };
  const selectAllGuides = () => { setActiveId(null); setQuery(""); setOpenSections(sections.map((section) => section.id)); setMenuOpen(false); };
  const toggleSection = (id: string) => setOpenSections((current) => current.includes(id) ? current.filter((section) => section !== id) : [...current, id]);

  return <main className="app-shell">
    <aside className={menuOpen ? "sidebar mobile-open" : "sidebar"} aria-label="Guide navigation">
      <div className="sidebar-brand"><span className="brand-block">B</span><div><strong>B Co 2-485</strong><small>Soldier Guide</small></div><button className="collapse-button" onClick={() => setMenuOpen(false)} aria-label="Collapse guide menu">‹</button></div>
      <p className="sidebar-tagline">Administrative, digital-access, and readiness resources</p>
      <label className="sidebar-search"><span>⌕</span><input value={query} onChange={(event) => { setQuery(event.target.value); setActiveId(null); }} placeholder="Search guides" aria-label="Search all guides" /></label>
      <nav className="guide-nav">
        <button className={activeId ? "all-guides" : "all-guides active"} onClick={selectAllGuides}><span>▦</span>All Guides <b>{guides.length}</b></button>
        {sections.map((section) => {
          const children = filtered.filter((guide) => guide.section === section.id);
          const isOpen = openSections.includes(section.id) || query.length > 0;
          return <div className="nav-section" key={section.id}>
            <button className={active?.section === section.id ? "nav-section-button section-active" : "nav-section-button"} onClick={() => toggleSection(section.id)} aria-expanded={isOpen}><span className="nav-icon">{section.icon}</span><span>{section.title}</span><b>{isOpen ? "⌄" : "›"}</b></button>
            {isOpen && <div className="sub-guides">{children.map((guide) => <button key={guide.id} onClick={() => selectGuide(guide.id)} className={activeId === guide.id ? "sub-guide selected" : "sub-guide"}>{guide.title}</button>)}{children.length === 0 && <span className="no-guide">No matches</span>}</div>}
          </div>;
        })}
      </nav>
      <div className="sidebar-bottom"><span className="green-dot"></span><div><strong>Reference only</strong><small>Official guidance takes precedence.</small></div></div>
    </aside>

    <section className="article-shell">
      <header className="article-header"><button className="mobile-menu" onClick={() => setMenuOpen(true)} aria-label="Open guide menu">☰</button><div className="breadcrumbs"><span>{active ? sections.find((section) => section.id === active.section)?.title : "Guide Library"}</span><b>/</b><strong>{active?.title ?? "All Guides"}</strong></div><div className="article-actions">{active ? <><span className={`status-pill status-${active.status}`}>{statusDetails[active.status].label}</span>{active.updated !== "Pending" && <span className="checked-date">Checked {active.updated}</span>}</> : <span>{guides.length} guides · {sections.length} sections</span>}{active && <button onClick={() => window.print()}>▣ Print</button>}</div></header>
      {active ? <article className="article-content">
          <div className="article-main">
            <button className="back-to-library" onClick={selectAllGuides}>← All guides</button>
            <span className="article-eyebrow">HOW-TO GUIDE</span><h1>{active.title}</h1><p className="article-summary">{active.summary}</p>
            <section className={`source-status source-status-${active.status}`} aria-label="Guide source status"><div><span className={`status-pill status-${active.status}`}>{statusDetails[active.status].label}</span>{active.updated !== "Pending" && <small>Sources checked {active.updated}</small>}</div><p>{active.sourceNote ?? "This guide is a working draft. Confirm the process against current official guidance and unit procedures before relying on it."}</p></section>
            <section className="before-card" id="before"><div className="before-title"><span>!</span><h2>Before you begin</h2></div><div className="before-items">{active.before.map((item) => <div key={item}><span>◌</span>{item}</div>)}</div></section>
            <section className="steps" id="steps">{active.steps.map((step, index) => <div className="step" key={step.title}><div className="step-number">{index + 1}</div><div className="step-copy"><h2>{step.title}</h2><p>{step.text}</p>{(step.links ?? (step.link ? [step.link] : [])).length > 0 && <div className="step-links">{(step.links ?? (step.link ? [step.link] : [])).map((link) => <a className="official-link" key={link.label} href={link.href} target="_blank" rel="noreferrer">↗ {link.label}</a>)}</div>}</div>{step.expect ? <div className="step-expect"><strong>WHAT YOU SHOULD SEE</strong><span>{step.expect}</span></div> : <div className="screen-placeholder" aria-label={`Visual pending for step ${index + 1}`}><span>VISUAL PENDING</span><i></i><i></i><i></i></div>}</div>)}</section>
            <section className="problems" id="problems"><div className="problem-heading"><span>!</span><h2>Common problems</h2></div><ul>{active.problems.map((problem) => <li key={problem}>{problem}</li>)}</ul></section>
            <section className="official-sources" id="sources"><h2>Official resources</h2>{active.official.length ? <div>{active.official.map((link) => <a key={link.label} href={link.href} target="_blank" rel="noreferrer">{link.label}<span>↗</span></a>)}</div> : <p>Official sources have not yet been attached to this draft. Use current Army and local command guidance before completing the task.</p>}{active.helpful?.length ? <div className="helpful-sources"><h3>Additional help — nonofficial</h3><p>These independent sites can help with troubleshooting, but Army and Microsoft sources take precedence.</p><div>{active.helpful.map((link) => <a key={link.label} href={link.href} target="_blank" rel="noreferrer">{link.label}<span>↗</span></a>)}</div></div> : null}</section>
            <footer className="article-footer"><strong>B Co 2-485 Soldier Guide</strong><p>Unofficial reference. Official Army guidance, local command policy, and the current version of every system take precedence.</p><small>This site does not collect or store information.</small></footer>
          </div>
          <aside className="on-page"><strong>ON THIS PAGE</strong><a href="#before">Before you begin</a><a href="#steps">Instructions</a><a href="#problems">Common problems</a><a href="#sources">Sources</a><button onClick={selectAllGuides}>Browse all guides →</button></aside>
        </article> : <article className="library-page">
          <div className="library-intro"><span className="article-eyebrow">GUIDE LIBRARY</span><h1>All Guides</h1><p>Find the task you need, follow the steps, and use the official resource links when provided.</p><div className="reference-banner"><span>i</span><div><strong>Unit reference—not an official Army publication</strong><small>Always follow current Army guidance and local command policy.</small></div></div></div>
          <label className="library-search"><span>⌕</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search by task, system, or topic" aria-label="Search the guide library" />{query && <button onClick={() => setQuery("")} aria-label="Clear search">Clear</button>}</label>
          <div className="library-stats"><div><strong>{filtered.length}</strong><span>{query ? "matching guides" : "available guides"}</span></div><div><strong>{guides.filter((guide) => guide.status === "source-verified").length}</strong><span>source-verified guides</span></div><div><strong>No login</strong><span>no information stored</span></div></div>
          <div className="guide-groups">{sections.map((section) => {
            const children = filtered.filter((guide) => guide.section === section.id);
            if (!children.length) return null;
            return <section className="guide-group" key={section.id}><div className="group-heading"><span>{section.icon}</span><div><h2>{section.title}</h2><small>{children.length} {children.length === 1 ? "guide" : "guides"}</small></div></div><div className="guide-cards">{children.map((guide) => <button className="guide-card" key={guide.id} onClick={() => selectGuide(guide.id)}><div><span className={`status-pill card-status status-${guide.status}`}>{statusDetails[guide.status].short}</span><h3>{guide.title}</h3><p>{guide.summary}</p></div><footer><span>{guide.time}</span>{guide.updated !== "Pending" && <span>Checked {guide.updated}</span>}<b>Open guide →</b></footer></button>)}</div></section>;
          })}</div>
          {!filtered.length && <div className="empty-results"><strong>No guides match “{query}”</strong><p>Try a system name such as AVD, IPPS-A, DTS, PDF, or NCOER.</p><button onClick={() => setQuery("")}>Clear search</button></div>}
          <footer className="article-footer library-footer"><strong>B Co 2-485 Soldier Guide</strong><p>Administrative, digital-access, and readiness resources for Soldiers and leaders.</p><small>This site does not collect or store information.</small></footer>
        </article>}
    </section>
  </main>;
}
